### ISSUE TITLE
 I use my ip address to visit '/v1/armory/getunsigned' api,will make a error

### ISSUE THREAD

**Issue by luoxiandong** [OmniLayer/omniapi#4]
Traceback (most recent call last):
  File "./armory_service.py", line 9, in <module>
    from armoryengine.ALL import *
ImportError: No module named armoryengine.ALL

i can not find module armoryengine,how to install or find it?

**Comment by achamely** [comment]
@luoxiandong can you provide more details of what's going on/the exact syntax of the api call you are performing? 
Are you trying to query the public api endpoint or are you trying to setup the project locally?
If you are trying to setup locally the armory library install instructions are detailed in the Readme: https://github.com/OmniLayer/omniapi#install-instructions
