### ISSUE TITLE
How to setup Postgres DB to fit the needs?

### ISSUE THREAD

**Issue by antoncoding** [OmniLayer/omniapi#6]
I've been trying to build the project from scratch, I already started:
* an omni-core client
* an **empty** Postgres DB
* a Redis server

and ran the `startApi.sh` script successfully. But when POST my localhost, the following error occured (in `apps.log`):

```
WSGI app 0 (mountpoint='localhost|/v1/address/addr') ready in 0 seconds on interpreter 0x23c9120 pid: 1474
Error relation "blocks" does not exist
LINE 1: select blocknumber, blocktime from blocks order by blocknumb...
                                           ^
 Rollback returned:  1
DAMN ! worker 9 (pid: 1474) died :( trying respawn ...
Respawned uWSGI worker 9 (new pid: 1618)
```

It seems like the DB is not set up correctly and not updating data from Omnicore. Is there a script to create all the relations in the DB or am I missing something?

**Comment by achamely** [comment]
@antoncoding everything related to setting up the database and updating it is in the OmniEngine project. That is the guts and brain behind the database. 
Most of the documentation is actually listed under Omniwallet repo : https://github.com/OmniLayer/omniwallet#ubuntu-setup  
Specifically check the ubuntu-setup section for descriptions of the layout and then the manual install section for more in depth information
