### ISSUE TITLE
Dockerized OmniApi

### ISSUE THREAD

**Issue by LYNCSS** [OmniLayer/omniapi#7]
Hello, I discovered a little issue while i was dockerizing those service. I decomposed those services into:

1. Omnicore
2. Omniengine
3. OmniAPI
4. Database
5. Redis

About OmniAPI, I used the scripts from here, the purpose was that I can disable the rate limit for personal usage. I mended the content of `omniapi/api/config.py` to adjust redis client configuration REDIS_HOST from `'localhost'` to the name `'redis'` service ran in docker-compose file.

After the test, it showed something wrong. The content in `apps.log` is shown below:
`WSGI app 0 (mountpoint='localhost|/v1/decode') ready in 0 seconds on interpreter 0x558ee37c76e0` `pid: 59`
`Traceback (most recent call last):`
`  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__`
`    return self.wsgi_app(environ, start_response)`
`  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app`
`    response = self.handle_exception(e)`
`  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception`
`    reraise(exc_type, exc_value, tb)`
`  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app`
`    response = self.full_dispatch_request()`
`  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request`
`    rv = self.handle_user_exception(e)`
`  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception`
`    reraise(exc_type, exc_value, tb)`
`  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request`
`    rv = self.dispatch_request()`
`  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request`
`    return self.view_functions[rule.endpoint](**req.view_args)`
`  File "./flask_rate_limit.py", line 64, in rate_limited`
`    rlimit = RateLimit(key, limit, per, send_x_headers, ipaddress)`
`  File "./flask_rate_limit.py", line 36, in __init__`
`    self.current = min(p.execute()[0], limit)`
`  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 2894, in execute`
`    return execute(conn, stack, raise_on_error)`
`  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 2749, in _execute_transaction`
`    connection.send_packed_command(all_cmds)`
`  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 585, in` `send_packed_command`
`    self.connect()`
`  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 489, in connect`
`    raise ConnectionError(self._error_message(e))`
`redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested ``address.`
`localhost [pid: 59|app: 0|req: 1/1] 192.168.48.1 () {46 vars in 660 bytes} [Wed Jun 19 08:16:17 2019]` `POST /v1/decode/ => generated 0 bytes in 259 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)`
`packet_write_wait: Connection to 3.16.82.177 port 22: Broken pipe`

It seemed that the script was still trying to connect to the localhost Redis server. However, there was no localhost Redis server and I had already mended the content in `omniapi/api/config.py`. And the log showed the error was occurred in `omniapi/api/flask_rate_limit.py`. I decided to look for some clues in the script. After that I found the code line: `redis=lInit(1)`. I thought it might be the reason for the error. I added a function `def rInit_From_Config(db)` to `omniapi/api/cacher.py` that the whole part of the function is shown below:
`def rInit_From_Config(db):`
`  try:`
`    dbk = int(db)`
`    if dbk == config.REDIS_DB:`
`      dbk = dbk + 1`
`  except:`
`    dbk = 1`
`  return redis.StrictRedis(host=config.REDIS_HOST, port=config.REDIS_PORT, db=dbk)`

Then, I change the code line `redis=lInit(1)` in `omniapi/api/flask_rate_limit.py` to `redis=rInit_From_Config(1)`, it solved.

So maybe it is a bug? if it is, then I want to report it. Thank you very much for the useful code.

**Comment by LYNCSS** [comment]
I found more problem when the api was running. In the scripts, it always operated as local Redis server. eg. lGet()
To solve it as fast as possible, I decided to change the code line in `cacher.py` from
`l = redis.StrictRedis()` to
`l = redis.StrictRedis(host=config.REDIS_HOST, port=config.REDIS_PORT, db=config.REDIS_DB)`

**Comment by achamely** [comment]
@LYNCSS thank you for the feedback. This is not really a bug but actually a specific design implementation choice. 

We specifically setup the `r` functions to reference a remote redis server and `l` functions reference a local redis server.  The local redis server was designed to cache the most frequently accessed data so it can be used to optimize response times. The remote redis server is used to offload some of the data processing that is handled by other services/process, specifically remote btc balance/data lookups. 

If you need to run the 'local' redis on a separate instance then your changes would work
